### PR TITLE
Updates by Samir Musali

### PR DESCRIPTION
**Pull request by smusali**
This Pull Request contains the following:
- [8369a60](https://github.com/smusali/MTAT.03.083/commit/8369a6016359bc2535ec0d7b01b9d3512cee3659): update: update my own solutions
- [986ce3c](https://github.com/smusali/MTAT.03.083/commit/986ce3ce375b1671c545e8d3a1a7f6b77a678fc0): update: update docs

### CODE REVIEW

**Comment by familbabayev** [comment]
What is difference between transaction status and payment status? aren't they the same thing?

**Comment by familbabayev** [comment]
image

Would it be better if we do like this?
removing transaction status enum
moving amount from Order class to Payment
moving payment status from Order class to Payment

**Comment by EldanizAkbar** [comment]
> image
> 
> Would it be better if we do like this? removing transaction status enum moving amount from Order class to Payment moving payment status from Order class to Payment

Your proposed changes seem to make sense. By removing the transaction status enum, moving the amount from the Order class to Payment, and moving the payment status from the Order class to Payment, we can achieve better organization and separation of concerns. This can lead to a more structured and maintainable codebase.

**Comment by smusali** [comment]
All sounds good. I think, what we have satisfies the requirements of the Assignment but let's avoid ambigiutiy.

**Pull request merged**
