### PR TITLE
Task 5 done

### PR DESCRIPTION
**Pull request by mushfugsoltanov**

### CODE REVIEW

**Comment by EldanizAkbar** [comment]
I noticed that the link to 'task5.pdf' is not working.  Could you please fix the link or provide an alternative way for us to access 'task5.pdf'?

**Comment by mushfugsoltanov** [comment]
> I noticed that the link to 'task5.pdf' is not working. Could you please fix the link or provide an alternative way for us to access 'task5.pdf'?

I put in text format. check [pdf changed to txt file](https://github.com/smusali/MTAT.03.083/pull/2/commits/522adb4a08d457b30e2c2e712258004039e2a569)

> I noticed that the link to 'task5.pdf' is not working. Could you please fix the link or provide an alternative way for us to access 'task5.pdf'?

**Comment by EldanizAkbar** [comment]
> > I noticed that the link to 'task5.pdf' is not working. Could you please fix the link or provide an alternative way for us to access 'task5.pdf'?
> 
> I put in text format. check [pdf changed to txt file](https://github.com/smusali/MTAT.03.083/pull/2/commits/522adb4a08d457b30e2c2e712258004039e2a569)
> 
> > I noticed that the link to 'task5.pdf' is not working. Could you please fix the link or provide an alternative way for us to access 'task5.pdf'?

I saw it. But I also want to see pdf version of it.

**Comment by mushfugsoltanov** [comment]
> > > I noticed that the link to 'task5.pdf' is not working. Could you please fix the link or provide an alternative way for us to access 'task5.pdf'?
> > 
> > 
> > I put in text format. check [pdf changed to txt file](https://github.com/smusali/MTAT.03.083/pull/2/commits/522adb4a08d457b30e2c2e712258004039e2a569)
> > > I noticed that the link to 'task5.pdf' is not working. Could you please fix the link or provide an alternative way for us to access 'task5.pdf'?
> 
> I saw it. But I also want to see pdf version of it.

check maybe

**Pull request merged**
